pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:CharityLearning/moodle-format_tiles.git
             - git checkout master
             - git pull    
             - git push --force sync master
      moodle43:
        - step:
           script:
             - git remote add sync git@github.com:CharityLearning/moodle-format_tiles.git
             - git checkout moodle43
             - git pull    
             - git push --force sync moodle43
      moodle44:
        - step:
           script:
             - git remote add sync git@github.com:CharityLearning/moodle-format_tiles.git
             - git checkout moodle44
             - git pull    
             - git push --force sync moodle44
      moodle45:
        - step:
           script:
             - git remote add sync git@github.com:CharityLearning/moodle-format_tiles.git
             - git checkout moodle45
             - git pull    
             - git push --force sync moodle45